name: Build and release

on:
  push:
    tags:
    - 'v*'

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Move artifacts and zip them
      run: mkdir Archie && cp target/*.jar Archie && cp -r target/lib Archie && zip -r Archie.zip Archie
    - name: Create release and upload
      uses: ncipollo/release-action@v1.20.0
      with:
        artifacts: Archie.zip
